### ISSUE TITLE
添加广告屏蔽功能

### ISSUE THREAD

**Issue by Silverteal** [waterblock79/aerfaying-explore#10]
相关API为/WebApi/Projects/GetAdRandomList

**Comment by Gtd232** [comment]
确实不错（

**Comment by waterblock79** [comment]
已添加功能，现在会自动找到评论区的奥的灰烬推荐（匹配`.comment_handleBtn_hP56Y > span.icon.icon-lg`）、发现页及作品页奥的灰烬推荐（匹配`.project-ads_ad_1uy0F`）并进行隐藏。

需要手动在控制台进行开启：

```javascript
// 屏蔽奥的灰烬推荐
localStorage.setItem('explore:no_ads', 'on');
// 不屏蔽
localStorage.setItem('explore:no_ads', null)
