### ISSUE TITLE
能否将最近升级的功能加个开关并放到“插件设置”里？

### ISSUE THREAD

**Issue by Gtd232** [waterblock79/aerfaying-explore#11]

**Comment by waterblock79** [comment]
这些功能吗：

1. [控制台插件提示及安全警告](https://github.com/waterblock79/aerfaying-explore/commit/50f6ad28938ec1578fa402a487eb0a74d6cce4c4)

2. [去除个人主页简介的 max-width 限制](https://github.com/waterblock79/aerfaying-explore/commit/29c3675eff2486357f98a8bbbe9d6e241051d41b)

**Comment by Gtd232** [comment]
第二个我觉得有必要

**Comment by Gtd232** [comment]
还有隐藏奥灰推荐位的功能

**Comment by waterblock79** [comment]
> 还有隐藏奥灰推荐位的功能

这个的开关其实是隐藏式的（

[#10 添加广告屏蔽功能](/waterblock79/aerfaying-explore/issues/10#issuecomment-1146609189_) 中：
```
// 屏蔽奥的灰烬推荐
localStorage.setItem('explore:no_ads', 'on');
// 不屏蔽
localStorage.setItem('explore:no_ads', null)

**Comment by waterblock79** [comment]
> 第二个我觉得有必要

这个默认开启的，也要加个开关吗（？

**Comment by Gtd232** [comment]
因为有些人主页太长了，翻也不好翻，而且A营现在原本就是限制的（

**Comment by Gtd232** [comment]
最好还是加个（

**Comment by Gtd232** [comment]
肯定有人不想看那么长的主页，翻得烦死了（

**Comment by Gtd232** [comment]
奥灰的那个，设计的明了一点吧，毕竟要在控制台改，而且像Safari不装插件根本改不了，有些人也不会改（

**Comment by waterblock79** [comment]
![image](https://user-images.githubusercontent.com/33573572/173082131-622e86f7-641f-4014-b7c8-edac611f0e5e.png)

已经开始尝试做这个功能了，我发现可能个人简介里面额外加一个滚动（如图）效果也不错，你觉得咋样（

**Comment by waterblock79** [comment]
不写了不写了，太难调了，我中考完再说吧

**Comment by Gtd232** [comment]
不错（  
中考加油（

**Comment by waterblock79** [comment]
给去除长度限制在插件设置中添加了一个开关（
