### ISSUE TITLE
能否增加小屏的情况下显示主页金币数量的功能

### ISSUE THREAD

**Issue by Gtd232** [waterblock79/aerfaying-explore#13]

**Comment by waterblock79** [comment]
![image](https://user-images.githubusercontent.com/33573572/172974753-579aff33-2989-4aa9-83dc-de4e3306097c.png)

（？

**Comment by Gtd232** [comment]
我的意思是，屏幕比较小（准确点是宽度小），主页上面不是会显示个人信息吗，但小屏幕的情况下不会显示金币

**Comment by Gtd232** [comment]
就比如手机上看不到主页显示的金币数量

**Comment by waterblock79** [comment]
![image](https://user-images.githubusercontent.com/33573572/173082131-622e86f7-641f-4014-b7c8-edac611f0e5e.png)

已经开始尝试做这个功能了，我发现可能个人简介里面额外加一个滚动（如图）效果也不错，你觉得咋样（

**Comment by waterblock79** [comment]
已添加，感谢建议
