### ISSUE TITLE
新注册的从来没有换过头像的用户无法显示头像

### ISSUE THREAD

**Issue by Gtd232** [waterblock79/aerfaying-explore#15]
在评论区点击新注册的从来没有换过头像的用户的名字，出现的框框将无法显示头像

**Comment by Gtd232** [comment]
![IMG_8723](https://user-images.githubusercontent.com/79702405/174427048-16dc3fb5-0b73-40fe-af8d-cb195e999515.jpeg)

**Comment by waterblock79** [comment]
已修复，感谢反馈
