### ISSUE TITLE
增加一些功能

### ISSUE THREAD

**Issue by zeng-y-l** [waterblock79/aerfaying-explore#16]
增加功能：

- 跳转到邀请页面  
  于`/Users/123456`可以一键跳转到`/Users/123456/My/InvitedUsers`
- 快速复制  
  于`/Users/1`可以一键复制`[守护煮](/Users/1)`  
  于`/Projects/815511`可以一键复制`[荒岛生存](/Projects/815511)`
- 评论框自动扩大  
  评论框很小，只能放三行字。希望当评论框获取焦点或内容非空时，高度增加至300px。
- 简讯框逻辑更改  
  现在，评论区中，简讯框是hover名字时弹出，建议改为hover头像时弹出，防止误触  
  另外，简讯框会在个人主页链接中出现（见Sisst的主页），这是刻意的设计吗？此时，其会占用文档流。  
  建议简讯框使用Bootstrap的tooltip。

以上内容，我大多数都做过，但是写的很烂，而且抄袭了很多，因此没有发布。  
如果你们需要，我可以帮你们写。

另外，我的<https://gitee.com/Zeng_YL/scratch_addon>，也可以集成进去。

另外，你们都不用JQuery，这是刻意的吗？

**Comment by waterblock79** [comment]
我开发者控制台的元素页面右键点不动了，先回答一下问题吧（

- 收到，这样怎么样？
   ![image](https://user-images.githubusercontent.com/33573572/176835251-1b08b7a5-c6e1-449a-8fc7-79109c501518.png)
- 大概这样？
   ![image](https://user-images.githubusercontent.com/33573572/176835507-5446321f-e9c9-49c4-87e8-3cce5d81d78b.png)
- 会尝试的，不知道效果怎么样（
- ok；简讯框是匹配 `a.comment_name_2ZnFZ` 的，他主页的用户头像外面使用了带`comment_name_2ZnFZ`的`a`标签，所以会被误判为是“评论用户名”；bootstrap 的 tooltip 貌似只能显示它自带的类似于：![image](https://user-images.githubusercontent.com/33573572/176836596-c0990b37-999b-4707-be68-46cdfad4fa41.png) 的样式，展现的信息比较单调（

- 感谢，等我右键好了会尝试集成一下的（

- 不是，是我没想起来这茬

**Comment by waterblock79** [comment]
我开发者控制台的右键好了，是我把开发者控制台缩放了...

**Comment by zeng-y-l** [comment]
好。

个人主页的邀请、一键复制、以及查看Markdown，可以类似这样：
![image](https://user-images.githubusercontent.com/89503645/176837891-5a31afb1-7971-40d9-862b-7835f10b9a73.png)

作品页面的复制按钮，你的排版很好。

**Comment by zeng-y-l** [comment]
使用JQuery，可以避免往每一个元素分别添加`EventListener`，仅需`$(document).on("事件", "选择器", 回调)`即可，省下一个`setInterval`。

另外，为了性能，大多数`setInterval`都可以用某种钩子（Hook）替代（以下所有建议都是为了性能）：

- 最好的就是直接Hook，例如要篡改ajax的返回内容，可以`$.ajaxPrefilter`后覆盖success回调
- 没有直接Hook，就间接Hook。例如评论区，先Hook评论请求的ajax，在success回调中`queueMicrotask`，届时就能看到渲染好的评论
- 个人总结一种间接Hook的办法：短期`setInterval`。例如，有的页面，请求后，要多个事件循环才渲染，`queueMicrotask`用不了。此时可以在success回调中`setInterval`，等待渲染好后`clearInterval`。
- 没有办法短期`setInterval`的，可以试试`MutationObserver`。
- 大杀器：`requestIdleCallback`

**Comment by waterblock79** [comment]
自动调整输入框的 height：

![xd](https://user-images.githubusercontent.com/33573572/180596918-c0180b8d-534f-4197-9f06-e2200a3fc5b2.gif)

跳转邀请页面：

![image](https://user-images.githubusercontent.com/33573572/180597212-e1bcb069-d7ab-41f4-921a-158509579191.png)

然后最近进行了一次完全的重构，提升了代码可读性，并且将原来零散的多个 Interval 更改为了统一的一个 Interval 来提升性能，自己造了一些轮子，不依赖于 jQuery 了。

用户简讯框的显示如果是在头像下面的话，会显得比较怪，就先不改了：

![image](https://user-images.githubusercontent.com/33573572/180598386-6a025e31-d122-4300-907a-998c13c1ea88.png)

**Comment by zeng-y-l** [comment]
很好！

但：

调整 height 暂未看到。

快速复制可以做做。

**Comment by waterblock79** [comment]
> 很好！
> 
> 但：
> 
> 调整 height 暂未看到。
> 
> 快速复制可以做做。

自动高度在 11 小时前推送的提交里：[🚀 更新插件设置布局；🚀 更新自适应输入框高度；🐛 修复无IP属地评论不显示评论ID的问题](/waterblock79/aerfaying-explore/commit/4482fc8a2f54eed2bfb862f3bf4f00ee85f20882)，快速复制功能我准备放在右下角：
![image](https://user-images.githubusercontent.com/33573572/180629050-d5b85d91-5c64-4214-af02-1a65f24b5f42.png)

**Comment by waterblock79** [comment]
已添加复制链接功能~
