### ISSUE TITLE
原用户简讯框功能将在 1.0.0 版本以后分离并单独提供

### ISSUE THREAD

**Issue by waterblock79** [waterblock79/aerfaying-explore#19]
用户简讯框功能可以让鼠标悬停在用户名链接上时，显示一个展示用户基础信息的小框

![image](https://user-images.githubusercontent.com/33573572/179521385-120be6c1-f315-48ea-af80-9a0b54b64188.png)

但在日常的使用中，我发现此功能貌似并不太实用，并且此功能有一定的不稳定性，故将该功能分离并单独进行提供。

- [Github Raw - aerfaying-explore-userbox.user.js](https://github.com/waterblock79/aerfaying-explore/raw/main/aerfaying-explore-userbox.user.js)
- [jsDeliver CDN](https://fastly.jsdelivr.net/gh/waterblock79/aerfaying-explore@master/aerfaying-explore-userbox.user.js)

**Comment by Gtd232** [comment]
谢谢你！谢谢你！谢谢你！
