### ISSUE TITLE
add switchers to every features

### ISSUE THREAD

**Issue by Silverteal** [waterblock79/aerfaying-explore#2]
我在使用Silverteal/Aerfaying-Evolved，它也有一个评论ID显示功能，但是这个脚本的评论ID显示功能不能关，就会出现两个评论ID显示......
我没有能力给Silverteal/Aerfaying-Evolved制作开关，所以就~~厚颜无耻地~~来请求开关功能......

**Comment by waterblock79** [comment]
已添加 :p，见：[🆕 支持开关评论 ID 显示功能](/waterblock79/aerfaying-explore/commit/1878f5fc4a6b2026f1d9bfc6575632e5ff0879f1)。
