### ISSUE TITLE
“邀请”似乎并没有显示正确及部分奇妙问题

### ISSUE THREAD

**Issue by Gtd232** [waterblock79/aerfaying-explore#21]
- 是加载完成的：  
![图片](https://user-images.githubusercontent.com/79702405/180206337-b3852d79-3dba-4922-ac2d-92014c28c0f5.png)  

 - 但没有显示：  
 
![图片](https://user-images.githubusercontent.com/79702405/180206399-a06a7298-7afc-41c4-acce-41aa7dec33de.png)  

（如果是故意为之建议加个显示）  

 - 此外，在<https://aerfaying.com/Users/1156029/My/InvitedUsers>界面似乎一直在加载：  
 
![图片](https://user-images.githubusercontent.com/79702405/180206481-5bfc4676-3c40-4f52-b97a-79c04266d7ad.png)
![图片](https://user-images.githubusercontent.com/79702405/180206510-597ca7e9-5f27-46ed-8195-df17ecf85c0d.png)

**Comment by Gtd232** [comment]
另外在评论编辑后不刷新似乎不会显示评论ID等信息：  
![图片](https://user-images.githubusercontent.com/79702405/180206872-e4c38f07-1b4d-4b4f-8f59-100e2a812211.png)

**Comment by Gtd232** [comment]
有的评论无法正常显示内容：  
![图片](https://user-images.githubusercontent.com/79702405/180207862-76020d90-6f08-41f6-832d-87e82c33acec.png)  
![图片](https://user-images.githubusercontent.com/79702405/180208228-727dd6ed-f8c0-43be-98af-32b929a5a2a6.png)  
![图片](https://user-images.githubusercontent.com/79702405/180208318-975737f0-4fe7-45ac-80d2-8dc92a8517b7.png)  
这个在A营是可以转跳的，而且好像也是md的用法之一  

附评论内容：  
```
<https://TFGS.AXOLOTL>
```

**Comment by Gtd232** [comment]
有时评论ID会出问题：  
![图片](https://user-images.githubusercontent.com/79702405/180209057-11ef2c95-2d3d-47fe-8d14-e918dff746c4.png)  
该选项为关闭，但有时刚编辑的评论或者刚发的评论不会显示ID了望修复~~唔唔唔~~

**Comment by Gtd232** [comment]
另外给备注的人的备注，在工作室里帖子板块，会显示两个，如下图：  
![IMG_9651](https://user-images.githubusercontent.com/79702405/180339810-4ad0300d-f2d1-4506-b979-92ce2e0851b2.jpeg)  
![IMG_9652](https://user-images.githubusercontent.com/79702405/180339870-fe3504d5-811e-4226-a9d9-3faa00a69ff9.jpeg)

**Comment by Gtd232** [comment]
而且在手机版视图上，“关注”“粉丝”和“邀请”不在一块儿：  
![IMG_9656](https://user-images.githubusercontent.com/79702405/180340589-0a06fbf1-e0eb-43fc-99e4-164fa035ccf8.jpeg)

**Comment by waterblock79** [comment]
1. 这个确实是故意设计的，我改成这样应该就不会误解了：
   ![image](https://user-images.githubusercontent.com/33573572/180388113-2c60e417-fddf-4089-a85a-f4e853e6a40f.png)

2. 这个一直会显示加载中的是因为最开始创建”加载中“这个元素的时候它就是显示着的，所以会在那里一直显示着，现在已经修复了。

3. 现在可以了，我把内容 encodeHTML 了一下：   
   ![image](https://user-images.githubusercontent.com/33573572/180393107-3b4dcb2b-1004-49f9-8ee8-eb9aec1e5feb.png)

4. 修好了，这个是因为这个名字的父级元素既有`user-info_wrapper_2acbL`又有`forum-post-card_creator_2rep0`，所以就添加了两遍，现在删除了多余的选择器就好了。
   ![image](https://user-images.githubusercontent.com/33573572/180393558-449bbab9-41a1-495d-a455-032e8bed3696.png)

5. 已修复
   ![image](https://user-images.githubusercontent.com/33573572/180395320-27200b16-f7b6-444f-b1ed-d2be6d946caf.png)

6. 评论 ID 的错误我改了下评论 ID 元素的位置，原来是在评论时间元素的内部，所以可能是更新评论时间的时候给评论 ID 弄没了，现在和评论时间元素是兄弟元素了，应该是修复了。
   
![image](https://user-images.githubusercontent.com/33573572/180400802-70603b86-ead1-4f7a-b583-7c0bc9d111dc.png)

**Comment by Gtd232** [comment]
谢谢你！谢谢你！谢谢你！
