### ISSUE TITLE
特定情况下“邀请”信息显示错误

### ISSUE THREAD

**Issue by Gtd232** [waterblock79/aerfaying-explore#22]
![图片](https://user-images.githubusercontent.com/79702405/180633871-6a07f31c-4b8d-4db8-8166-4091623cb3e3.png)
![图片](https://user-images.githubusercontent.com/79702405/180633896-a7a2c7e5-46bb-466a-8d00-88db7ef489ee.png)
![图片](https://user-images.githubusercontent.com/79702405/180633926-e03db9be-0217-484e-8a44-16a2c804536b.png)
![图片](https://user-images.githubusercontent.com/79702405/180633951-728e6c22-fdc9-4ff4-9fc5-5656fdd20c0b.png)
显而易见的，我并没有大号邀请了大号，这种情况在啊尔发应应该也不会诞生。  
所以能不能修复 一下

**Comment by waterblock79** [comment]
我这里阿儿法营和稽木世界都不会发生这个问题..?

![image](https://user-images.githubusercontent.com/33573572/180638142-50872f7c-529e-4604-8c37-5ec4c6e322b9.png)

![image](https://user-images.githubusercontent.com/33573572/180638149-f43b2017-f9e1-47c2-8edf-26e1038a49be.png)

这个问题也有其他用户反馈过了，但是“换台电脑”就好了，我也不知道怎么复现，如果可以的话请截图一下 `/WebApi/Users/*/GetPagedInvitedUsers` 相关的网络请求和控制台日志，谢谢！

**Comment by Gtd232** [comment]
第一步访问https://aerfaying.com/Users/1241586/My/InvitedUsers时：
![图片](https://user-images.githubusercontent.com/79702405/180644229-52a7403b-ccaf-453a-b43d-86d98e943820.png)
![图片](https://user-images.githubusercontent.com/79702405/180644495-4d3c1f32-b4ca-457a-9089-82bdd52534c6.png)
然后点https://user-images.githubusercontent.com/79702405/180633896-a7a2c7e5-46bb-466a-8d00-88db7ef489ee.png
![图片](https://user-images.githubusercontent.com/79702405/180644298-397f326d-4ec3-4ce9-b25b-900bf376f00f.png)
![图片](https://user-images.githubusercontent.com/79702405/180644570-30f53f60-7747-4983-a4cc-d5f485d36992.png)
最后点![图片](https://user-images.githubusercontent.com/79702405/180644584-478b127b-6348-4c08-8fc5-33949555ed14.png)
![图片](https://user-images.githubusercontent.com/79702405/180644602-6c618360-8bfa-4c4f-8b57-d2c7990a4999.png)
![图片](https://user-images.githubusercontent.com/79702405/180644613-0b713a33-c037-4c25-b720-d91730f3e298.png)
我最开始实在Safari上试的，随后在firefox、MS Edge上都试了，我还在用Safari时录了视频  
最后附/WebApi/Users/*/GetPagedInvitedUsers 相关的网络请求：

![图片](https://user-images.githubusercontent.com/79702405/180644741-56922ef7-015a-4e63-a384-e9ec3a877a05.png)
![图片](https://user-images.githubusercontent.com/79702405/180644759-f0ee2bab-ffd2-4b1a-b058-840ba0f38cdd.png)
（这个是我小号邀请界面的）
![图片](https://user-images.githubusercontent.com/79702405/180644776-d3a52b88-abe0-4218-9cbd-043958a7372b.png)
![图片](https://user-images.githubusercontent.com/79702405/180644785-b02d5c9f-fb34-4384-b84f-21d9c92f3eb4.png)
（这个是到了大号邀请界面的）

**Comment by Gtd232** [comment]
然后我要不再说下触发的具体步骤（？  
首先是到https://aerfaying.com/Users/1241586
点
![图片](https://user-images.githubusercontent.com/79702405/180644927-cd920c6a-a717-4f76-92c0-52aa33e4fe6c.png)
然后点
![图片](https://user-images.githubusercontent.com/79702405/180644984-ea2ce7e3-ab38-4d27-8ec0-ab9ceae44fed.png)
然后页面点
![图片](https://user-images.githubusercontent.com/79702405/180645004-3441872a-0110-4b86-b840-ec1a71391478.png)
然后就会这样：  
![图片](https://user-images.githubusercontent.com/79702405/180645035-fac73552-4701-4ed1-941e-ce51d3c9c824.png)

**Comment by Gtd232** [comment]
我不清楚这是否只对自己有效，所以你可以试试去被自己邀请的用户的主页试试:P

**Comment by waterblock79** [comment]
谢了，复现成功了，这个是因为脚本只会在刷新后获取一次用户 ID，然后尝试找到所有新出现的”加入时间“并在旁边放上这个邀请信息，所以如果这个用户是被邀请的，再去其他用户的主页的话，脚本还是会按照刷新后获取的那个用户信息，给不是被邀请的用户添加邀请信息，我重新实现了一遍这个功能，现在应该是可以了。
