### ISSUE TITLE
貌似显示评论id时，被回复的评论id会和最后一条回复评论id连接在一起而不是显示在被回复评论旁边

### ISSUE THREAD

**Issue by sceatcher3** [waterblock79/aerfaying-explore#23]
![Screenshot_20220724_220950_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/65064653/180651002-2686ca60-d13f-4978-9b1f-fc5f37617228.jpg)
![Screenshot_20220724_221321_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/65064653/180651066-f9e3621b-82de-4181-b2da-1cbf0318e794.jpg)
效果如图，被回复的评论id在最后一条回复评论id前面，不清楚是不是手机端的问题（切换桌面端网站时问题依然存在）
评论选择无恶意，只是看到了bug随手截的（

**Comment by sceatcher3** [comment]
水块快来修bug（bushi

**Comment by Gtd232** [comment]
电脑上也有，我之前也看到过

**Comment by Gtd232** [comment]
而且父评论也没显示了

**Comment by waterblock79** [comment]
感谢反馈！已修复这个问题。

这个是在根评论没有IP属地，但是回复评论却有IP属地时会出现的。根评论在找地方插入这个评论 ID 元素时候有一个特判判断评论是否有IP属地，然而这个特判的选择器选到了它的回复评论中，然后这个评论 ID 就插入到了它的第一个带IP属地的回复评论里，现在修改了选择器，这个选择器匹配元素更加精准了，应该就不会出现这样的问题了。

**Comment by waterblock79** [comment]
提及错issue了...
