### ISSUE TITLE
"邀请"栏在特定情况下不显示  

### ISSUE THREAD

**Issue by Gtd232** [waterblock79/aerfaying-explore#25]
可以通过以下方式触发:  
到<https://aerfaying.com/Explore/Projects>  
从上到下依次点击:  
![图片](https://user-images.githubusercontent.com/79702405/181906532-793e1869-afcc-48fe-a4fd-4121e67e2c10.png)  
将不会看到"邀请"栏:  
![图片](https://user-images.githubusercontent.com/79702405/181906543-fe28f1cb-e257-4747-b06d-d43c26f2a4b2.png)  
必须刷新后才行;   
  
  
求修复![图片](https://user-images.githubusercontent.com/79702405/181906571-2814bb4f-b557-4af1-a7c8-9fd55e91006c.png)

**Comment by waterblock79** [comment]
已修复，感谢反馈

**Comment by Gtd232** [comment]
9999

**Comment by waterblock79** [comment]
> 9999

6666
