### ISSUE TITLE
iPad Safari浏览器打开作品创作页加载中动画会变形

### ISSUE THREAD

**Issue by Saobby** [waterblock79/aerfaying-explore#26]
图:

![4C26F437-FE2D-4A83-9549-CCB6A5A3ECC8](https://user-images.githubusercontent.com/101960076/182009404-d1ad538c-42ab-4e46-b081-303e785bf143.jpeg)

版本:1.3.6

**Comment by Saobby** [comment]
版本 1.3.6

**Comment by Gtd232** [comment]
这个我上次跟他说过了_ _ _

**Comment by Gtd232** [comment]
是不是没有_ _ _ _ _ _ _修复

**Comment by Gtd232** [comment]
![IMG_9914](https://user-images.githubusercontent.com/79702405/182011529-f55119dd-3e1f-4142-9d84-03179fa4ee95.jpeg)

**Comment by waterblock79** [comment]
> ![IMG_9914](https://user-images.githubusercontent.com/79702405/182011529-f55119dd-3e1f-4142-9d84-03179fa4ee95.jpeg)

[修复普通页面上的变形问题](/waterblock79/aerfaying-explore/commit/609810e1187cffd10f4d31a09f808acada533ba1)了，没考虑到作品扁辑器的

![image](https://user-images.githubusercontent.com/33573572/182012235-f54440ca-4f2e-4d71-8807-f3d3efbc0156.png)


![image](https://user-images.githubusercontent.com/33573572/182012247-4ba13659-37c7-4394-91ca-a9beb3c27125.png)

**Comment by waterblock79** [comment]
![image](https://user-images.githubusercontent.com/33573572/182012453-57fe8ccf-24c7-451d-aa8a-d797eea3da79.png)

现在应该可以了，`"谢谢你！".repeat(9)`
