### ISSUE TITLE
设定备注的用户显示备注后头像有可能显示不出来

### ISSUE THREAD

**Issue by Gtd232** [waterblock79/aerfaying-explore#27]
![图片](https://user-images.githubusercontent.com/79702405/182022387-d735b285-4753-416e-9b83-f5fc777c3266.png)  

![图片](https://user-images.githubusercontent.com/79702405/182022408-77018d64-fa65-446a-a5d0-b62f4418fb64.png)  
同一个页面,其他的就能加载出来,唯独有备注不行.
有的时候刷新之前还有,刷新之后就没有

现在发现这些加载不出来的似乎都有备注

**Comment by Gtd232** [comment]
等半天也没用

**Comment by waterblock79** [comment]
![image](https://user-images.githubusercontent.com/33573572/182028358-38ed2d01-a77d-49be-bafb-67c124109f4d.png)


这个问题已经在最新版[修复](https://github.com/waterblock79/aerfaying-explore/commit/3924277fe077ab63ae5d9fdf5ac6bf41f8cca5c2#diff-352d8bf84064f9ee159d6e4920c96625957037deb9f967d89d4b751db38b5d4cL695-R694)了，更新即可.

这个是因为原来直接在 innerHTML 后面追加内容，导致图片终止加载

**Comment by Gtd232** [comment]
`"谢谢你！".repeat(9) `
