### ISSUE TITLE
建议在“物品”栏的手机显示界面增加“物品图鉴”和“拍卖行”

### ISSUE THREAD

**Issue by Gtd232** [waterblock79/aerfaying-explore#28]
手机界面上并没有点进去的入口，希望增下以下：  
![IMG_0072](https://user-images.githubusercontent.com/79702405/183249035-247c755a-0308-4f65-ac29-1796dd972f0e.jpeg)

**Comment by waterblock79** [comment]
已添加，感谢建议：

![image](https://user-images.githubusercontent.com/33573572/188259154-1b7f23c7-cfa2-4644-9d48-88d33524695f.png)
