### ISSUE TITLE
希望发帖界面的输入框不要自动缩小

### ISSUE THREAD

**Issue by Gtd232** [waterblock79/aerfaying-explore#29]
![图片](https://user-images.githubusercontent.com/79702405/183890371-5aa3e769-eafc-404d-8d60-da1e3a511b8c.png)
它自动缩小了,但缩小了更不方便.

**Comment by Gtd232** [comment]
感觉这个没必要自适应**缩小**(((  
![图片](https://user-images.githubusercontent.com/79702405/183890607-f24cd489-20fd-4f1a-9f90-05d3109afb4c.png)

**Comment by waterblock79** [comment]
已修复，感谢反馈（
