### ISSUE TITLE
希望添加查看有中精及以上作品曾经选票详情的功能

### ISSUE THREAD

**Issue by Gtd232** [waterblock79/aerfaying-explore#32]
对于中精及以上等级的作品，野营不支持查看过去的选票详情（如初精选票详情） 不过可以通过请求API的方式获取，希望该插件能通过请求API获取信息并显示到页面上，让用户方便、清晰地查看。  
API地址为`https://aerfaying.com/WebApi/Projects/<ProjectId>/GetEvaluates`（若没有请求荷载，可以获取各级精华选票；需要有效cookie）

**Comment by waterblock79** [comment]
感谢建议，已添加

![显示全部精华投票](https://github.com/waterblock79/aerfaying-explore/assets/33573572/29de2212-8f24-469b-9a2e-2067efdbfcb2)
