### ISSUE TITLE
再次出现两个用户信息框

### ISSUE THREAD

**Issue by Gtd232** [waterblock79/aerfaying-explore#5]
![image](https://user-images.githubusercontent.com/79702405/170817204-f362bc46-3408-4a2c-9ae4-b1f07bb6aed1.png)  
版本最新：
![image](https://user-images.githubusercontent.com/79702405/170817221-904b0afe-3141-4745-bfd5-8f96bb7cf606.png)   
有可能是因为之前没有加载过此人的信息，然后就这样了。

**Comment by waterblock79** [comment]
已修复，感谢
