### ISSUE TITLE
似乎有人因为做了破解主页最大长度限制被路障

### ISSUE THREAD

**Issue by Gtd232** [waterblock79/aerfaying-explore#7]
论剑锋某发布破解主页最大长度作者，在刚发布贴子时没有被路障（那时候我正好去他的主页了），后来SisST告诉我被路障了，确实在发帖后被路障了。很有可能跟这个有关。请谨慎做这个功能。

**Comment by waterblock79** [comment]
先这样弄着吧，我本来就觉得这个限制就很无理，这样也算是反对不合理机制的一种办法吧 XD 那位的路障我在管理员群里提出异议了，还没答复

**Comment by Gtd232** [comment]
好，我也觉得这个限制很无理，甚至不知道那个做了破解主页限制的人为什么要给路障XD

**Comment by waterblock79** [comment]
> 好，我也觉得这个限制很无理，甚至不知道那个做了破解主页限制的人为什么要给路障XD

先关 issue 了，到时候有问题再和他们协商了
