### ISSUE TITLE
建议添加批量放奥灰功能

### ISSUE THREAD

**Issue by Gtd232** [waterblock79/aerfaying-explore#8]
现在要一个一个放，真的很烦。  
我的大致思路是这样的：选用奥灰时，弹出窗口问要放几个，然后再根据用户选择的数量，向服务器发送相应数量的请求。望采纳。

**Comment by waterblock79** [comment]
不能做替用户进行操作的功能，一个是可能不符合规定，一个是出问题的责任承担不起（

**Comment by Gtd232** [comment]
好吧（
