### ISSUE TITLE
在特定条件下会出现无效数据

### ISSUE THREAD

**Issue by Gtd232** [waterblock79/aerfaying-explore#9]
![image](https://user-images.githubusercontent.com/79702405/171634559-31f13052-1038-49de-bdd8-80f748b6b07f.png)  
在使用网址带commentId，且评论是单独加载，不在上面的加载过的评论时（如下图），会出现上图的情况。在首次打开这些链接会出现这种情况，再次打开就有可能不出现。
![image](https://user-images.githubusercontent.com/79702405/171635457-8099e29f-0277-43a8-b28b-f40ff446c9fe.png)    
[测试链接](https://gitblock.cn/Users/1226979#commentId=4031598)

**Comment by Gtd232** [comment]
等下，经过我的测试在任何情况下，该用户数据没加载过都是这样，可能跟上述条件无关

**Comment by waterblock79** [comment]
不太好复现，能提供一下图里的URL吗（

**Comment by waterblock79** [comment]
第 71 行我写了一个判断是否保存了这个信息的，不知道为什么没生效？

```javascript
            // 如果这个用户的信息没被存下，那就发送请求获取数据
            if( window.userInfoCache[userId] == undefined ) {
                let cId = data.parentElement.parentElement.id; // 请求里面的 data 给代表这个链接元素的外面的 data 覆盖掉了......
                $.ajax({ url: `/WebApi/Users/${e.target.href.match(/[0-9]+/g)[0]}/Get`, method: 'post', success: (data) => {
                    addUserBox( data, cId );
                    // 存好这个用户的数据，下回就不再请求了
                    window.userInfoCache[userId] = data;
                } });
            } else {
                addUserBox( window.userInfoCache[userId], data.parentElement.parentElement.id )
            }

**Comment by Gtd232** [comment]
有时不会出现。我现在认为出现这个情况能不能提示一个“加载错误”，不然太生硬了（

**Comment by Gtd232** [comment]
现在又来了，这是一个使用奥灰的随机展览位上的用户名出现的：  
![image](https://user-images.githubusercontent.com/79702405/171838263-2bae5b65-21e8-49f6-afbb-c7b196e13baf.png)

**Comment by Gtd232** [comment]
这样测试：  
首先登录到gitblock.cn   
然后打开https://gitblock.cn/Users/1226979#commentId=4031598  
找到评论：
![image](https://user-images.githubusercontent.com/79702405/171843195-9aa401f9-f986-45cc-bdea-ff70cc887c61.png)  
然后试试。  
假如之前进行这个测试的话，再次测试就没问题。可过几天又会这样。

**Comment by Gtd232** [comment]
现在据我尝试，如果这个用户数据在本地没有储存，就会这样，刷新后这个用户的数据又好了（

**Comment by Gtd232** [comment]
当然我不是很清楚您写的代码，有没有可能它是加载完本地空数据渲染完再去发送请求的（

**Comment by waterblock79** [comment]
okok，我找到错误的原因了，已修复，感谢
